import { type Node, type Edge, MarkerType } from '@xyflow/react';

export const initialNodes: Node[] = [
  {
    id: 'hero',
    type: 'hero',
    position: { x: 420, y: 0 },
    data: {},
  },
  {
    id: 'philosophy',
    type: 'philosophy',
    position: { x: 410, y: 200 },
    data: {},
  },
  {
    id: 'inception',
    type: 'phase',
    position: { x: 20, y: 420 },
    data: {
      phase: 1,
      title: 'Inception',
      description: 'Transforms business intent into an AI-consumable plan through iterative PRD development.',
      steps: ['PRD Development', 'Kiro / Claude Code', 'Iterative Refinement', 'Constraint Definition'],
      color: '#3B82F6',
    },
  },
  {
    id: 'construction',
    type: 'phase',
    position: { x: 470, y: 420 },
    data: {
      phase: 2,
      title: 'Construction',
      description: 'Converts plans into code through disciplined cycles with mandatory context clearing.',
      steps: ['Constraint Review', 'Implementation', 'Testing & Lint', 'Commit', 'Context Clear'],
      color: '#8B5CF6',
    },
  },
  {
    id: 'operations',
    type: 'phase',
    position: { x: 920, y: 420 },
    data: {
      phase: 3,
      title: 'Operations',
      description: 'Deploy, monitor, and maintain systems using infrastructure-as-code.',
      steps: ['IaC Deploy', 'Monitoring', 'Maintenance', 'Feedback Loop'],
      color: '#10B981',
    },
  },
  {
    id: 'tenets',
    type: 'tenets',
    position: { x: 0, y: 740 },
    data: {
      tenets: [
        'AI proposes; humans validate',
        'Context-first approach',
        'Planning discipline',
        'Crash resilience',
        'Risk-based permissions',
        'Proactive context mgmt',
        'Atomic task design',
        'Dual verification',
        'Infrastructure investment',
        'Controlled complexity',
      ],
    },
  },
  {
    id: 'primitives',
    type: 'primitives',
    position: { x: 480, y: 740 },
    data: {
      dayOne: [
        'Tool Registries',
        'Permission Tiers',
        'Session Persistence',
        'Workflow State',
        'Token Budgets',
        'Streaming Events',
        'Event Logging',
        'Dual Verification',
      ],
      opMaturity: [
        'Tool Pool Assembly',
        'Transcript Compaction',
        'Permission Audits',
        'Agent Type Systems',
      ],
    },
  },
  {
    id: 'memory',
    type: 'memory',
    position: { x: 900, y: 740 },
    data: {
      tiers: [
        {
          tier: 1,
          name: 'Constitution',
          label: 'CLAUDE.md / .kiro/steering/',
          detail: 'Immutable constraints, standards, architecture',
        },
        {
          tier: 2,
          name: 'Case Law',
          label: '.claude/memory/ / .kiro/agents/',
          detail: 'Accumulated lessons, preferences, context',
        },
        {
          tier: 3,
          name: 'Live Testimony',
          label: 'Session state',
          detail: 'Ephemeral by design, active context only',
        },
      ],
    },
  },
  {
    id: 'aws',
    type: 'aws',
    position: { x: 340, y: 1140 },
    data: {
      services: [
        { name: 'Amazon Bedrock', role: 'Model infrastructure & inference' },
        { name: 'Kiro', role: 'Spec-driven IDE for Inception' },
        { name: 'Kiro CLI', role: 'Terminal agentic coding & agents' },
        { name: 'Amazon Q Developer', role: '/dev, /review, /transform, /doc' },
        { name: 'Strands Agents SDK', role: 'Implements the twelve primitives' },
        { name: 'AgentCore', role: 'Managed runtime for production' },
      ],
    },
  },
];

const edgeDefaults = {
  animated: true,
  style: { strokeWidth: 2 },
  markerEnd: { type: MarkerType.ArrowClosed, width: 16, height: 16 },
};

export const initialEdges: Edge[] = [
  {
    id: 'hero-philosophy',
    source: 'hero',
    target: 'philosophy',
    ...edgeDefaults,
    style: { ...edgeDefaults.style, stroke: '#6366F1' },
    markerEnd: { ...edgeDefaults.markerEnd, color: '#6366F1' },
  },
  {
    id: 'philosophy-inception',
    source: 'philosophy',
    target: 'inception',
    ...edgeDefaults,
    style: { ...edgeDefaults.style, stroke: '#3B82F6' },
    markerEnd: { ...edgeDefaults.markerEnd, color: '#3B82F6' },
  },
  {
    id: 'philosophy-construction',
    source: 'philosophy',
    target: 'construction',
    ...edgeDefaults,
    style: { ...edgeDefaults.style, stroke: '#8B5CF6' },
    markerEnd: { ...edgeDefaults.markerEnd, color: '#8B5CF6' },
  },
  {
    id: 'philosophy-operations',
    source: 'philosophy',
    target: 'operations',
    ...edgeDefaults,
    style: { ...edgeDefaults.style, stroke: '#10B981' },
    markerEnd: { ...edgeDefaults.markerEnd, color: '#10B981' },
  },
  {
    id: 'inception-construction',
    source: 'inception',
    target: 'construction',
    sourceHandle: 'right',
    targetHandle: 'left',
    type: 'smoothstep',
    ...edgeDefaults,
    label: 'plan ready',
    labelStyle: { fill: '#94A3B8', fontSize: 11, fontWeight: 500 },
    labelBgStyle: { fill: '#0F172A', fillOpacity: 0.85 },
    labelBgPadding: [6, 4] as [number, number],
    labelBgBorderRadius: 6,
    style: { ...edgeDefaults.style, stroke: '#6366F1', strokeWidth: 2.5 },
    markerEnd: { ...edgeDefaults.markerEnd, color: '#6366F1' },
  },
  {
    id: 'construction-operations',
    source: 'construction',
    target: 'operations',
    sourceHandle: 'right',
    targetHandle: 'left',
    type: 'smoothstep',
    ...edgeDefaults,
    label: 'code merged',
    labelStyle: { fill: '#94A3B8', fontSize: 11, fontWeight: 500 },
    labelBgStyle: { fill: '#0F172A', fillOpacity: 0.85 },
    labelBgPadding: [6, 4] as [number, number],
    labelBgBorderRadius: 6,
    style: { ...edgeDefaults.style, stroke: '#6366F1', strokeWidth: 2.5 },
    markerEnd: { ...edgeDefaults.markerEnd, color: '#6366F1' },
  },
  {
    id: 'inception-tenets',
    source: 'inception',
    target: 'tenets',
    ...edgeDefaults,
    style: { ...edgeDefaults.style, stroke: '#10B981', strokeDasharray: '6 3' },
    markerEnd: { ...edgeDefaults.markerEnd, color: '#10B981' },
  },
  {
    id: 'construction-primitives',
    source: 'construction',
    target: 'primitives',
    ...edgeDefaults,
    style: { ...edgeDefaults.style, stroke: '#8B5CF6', strokeDasharray: '6 3' },
    markerEnd: { ...edgeDefaults.markerEnd, color: '#8B5CF6' },
  },
  {
    id: 'operations-memory',
    source: 'operations',
    target: 'memory',
    ...edgeDefaults,
    style: { ...edgeDefaults.style, stroke: '#F59E0B', strokeDasharray: '6 3' },
    markerEnd: { ...edgeDefaults.markerEnd, color: '#F59E0B' },
  },
  {
    id: 'tenets-aws',
    source: 'tenets',
    target: 'aws',
    ...edgeDefaults,
    style: { ...edgeDefaults.style, stroke: '#F9731680' },
    markerEnd: { ...edgeDefaults.markerEnd, color: '#F97316' },
  },
  {
    id: 'primitives-aws',
    source: 'primitives',
    target: 'aws',
    ...edgeDefaults,
    style: { ...edgeDefaults.style, stroke: '#F9731680' },
    markerEnd: { ...edgeDefaults.markerEnd, color: '#F97316' },
  },
  {
    id: 'memory-aws',
    source: 'memory',
    target: 'aws',
    ...edgeDefaults,
    style: { ...edgeDefaults.style, stroke: '#F9731680' },
    markerEnd: { ...edgeDefaults.markerEnd, color: '#F97316' },
  },
];
